version: "3"

services:
  crud:
    build:
      context: .
      dockerfile: crud.Dockerfile
    image: crud-ws:latest
    env_file:
      - ./warm-up-crud/.env
    environment:
      - PORT=3002
      - TLS_PORT=4003
    volumes:
      - ~/.ssh:/root/.ssh-localhost:ro
    ports:
      - "3002:3000"
      - "9229:9229"
      - "4003:443"
    command: sh -c "npm install ts-node-dev -g && npm run debug"
    network_mode: "host"
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb:/data/db
    network_mode: "host"
